XcodesOrg/XcodesApp

Xcodes/Frontend/Preferences/UpdatesPreferencePane.swift
Fixes #67
Adds the word `app`, to be more clear about App pre releases vs Xcode pre releases.
=> Updates the App Update copy to be more relevant about app vs xcode

Xcodes/Backend/Version+XcodeReleases.swift, Xcodes/Frontend/XcodeList/InfoPane.swift, Xcodes/Frontend/XcodeList/XcodeListViewRow.swift
Fixes #72 
Removes the brackets when the `buildMetadataIdentifiers` property of version is empty.
For simplicity, I added a computed var on our extension for a display property. 
Added a few examples as well for completion.
=> Don't show brackets when buildMetadataIdentifiers is empty

Xcodes/Frontend/MainWindow.swift
Closes #71 
Update the Filter and info button to use Appstorage instead of SceneStorage.
Only download I really see now, is in the multiple window situation, updating one, automatically updates the others.
=> #71 Update Filter/Info to use AppStorage

Xcodes.xcodeproj/project.pbxproj, Xcodes/Backend/AppState+Install.swift, XcodesTests/AppStateTests.swift
This change catches the xip error that is output when there's not enough free space to expand a .xip archive and makes sure that it's presented with a better error message.
It also adds AppStateTests to the XcodesTests target, not sure what happened there.
|Before|After|
|-----|-----|
|![Screen Shot 2021-01-23 at 11 17 25 AM](https://user-images.githubusercontent.com/594059/105610884-50021980-5d6f-11eb-9da5-8e43a1de0b74.png)|![Screen Shot 2021-01-23 at 11 32 41 AM](https://user-images.githubusercontent.com/594059/105610888-54c6cd80-5d6f-11eb-9f55-0925a3d837c7.png)|
Closes #77
=> Catch and reword xip "not enough free space" error

Xcodes/Backend/AppState+Install.swift, Xcodes/Backend/AppState.swift, Xcodes/Backend/Environment.swift, Xcodes/Backend/HelperClient.swift, Xcodes/Frontend/Preferences/AdvancedPreferencePane.swift
Instead of ignoring errors (either cancellation or failure) from helper installation, this change throws them so callers can react appropriately. Previously, whatever was being done that required the helper would proceed as if installation succeeded, which would always fail. Now, cancellation or failures will complete the subscriptions without attempting the next steps, and without showing more errors to the user. The initial error, for example cancellation in the below screenshot, will still be shown.
The second commit makes a small change to how auth error messages are created to avoid describing the optional wrapper type with `Optional(...)`.
|after cancelling helper installation|
|-----|
|![Screen Shot 2021-01-23 at 1 51 35 PM](https://user-images.githubusercontent.com/594059/105613792 …
=> Handle helper installation errors

Xcodes/Frontend/Common/ProgressIndicator.swift, Xcodes/Frontend/XcodeList/InstallationStepView.swift
I didn't like not knowing what percent my download was at, so a quick win is to show it on the tooltip
=> Show ToolTip on progress indicator

Xcodes.xcodeproj/project.pbxproj, Xcodes/Backend/AppState+Install.swift, Xcodes/Backend/AppState.swift, Xcodes/Backend/HelperInstallState.swift, Xcodes/Frontend/MainWindow.swift, Xcodes/Frontend/Preferences/AdvancedPreferencePane.swift, Xcodes/Frontend/XcodeList/XcodeListViewRow.swift, XcodesTests/AppStateTests.swift
The intent of this change is to make sure users are prepared to enter their macOS account password in the helper installation alert so that they aren't surprised and cancel installation, which leads to further failures.
This affects making Xcode versions active and the "step 6: finishing" post-install steps of installation.
The implementation of these changes aren't straightforward (I think), as most of the logic is implemented in publishers that now have to wait on user interaction in the preparation alert. This is done in two different ways because the way these methods are invoked is a little different:
- `select(id:shouldPrepareUserForHelperInstallation:)` is invoked once and returns early to prepare the user. Once the user makes a decision in the preparation alert the method is …
=> Prepare user for helper installation before attempting to install

Xcodes/AppleAPI/Sources/AppleAPI/Client.swift, Xcodes/Backend/AppState.swift, Xcodes/Frontend/About/AboutView.swift, Xcodes/XcodesApp.swift
This PR makes two changes:
Improve how auth errors are shown in an Alert. They all provide their own descriptions now, where before some of them would default to String(describing:) which didn't do a great job. I also removed some of the associated values from the descriptions because while it might be useful for debugging, it is not immediately helpful for users. We may want to find another way to provide users with this information, even if it's how to find it in Console.app, in the future. A 400 status code during security code submission is now treated as an "incorrect code" error. I'm not sure why it wasn't before, as I thought this implementation was just taken from xcodes, but when I tested this situation I got a 400 instead of a 401.
Added bug report and feature request items to …
=> Improve authentication error messages that are shown to users

Xcodes/Backend/AppState.swift, Xcodes/Frontend/Preferences/GeneralPreferencePane.swift
This reverts the change from 90c067997bdd3e1e3a18c7896baa6d119fcc61ba (in #45) so that the username is shown in situations where we don't have a valid session but could almost certainly get one. Instead, to achieve what that commit was trying to do (not appear signed in when auth failed), we'll instead remove the username from UserDefaults if auth fails with an invalid username or password error. I think this will more closely match what users expect in this UI.
I've added a comment in the UI explaining why it is the way it is. It might also be worth considering renaming AuthenticationState or its cases to better reflect that it's probably more about the (short-lived) session state than whether the user has signed in before and has stored their credentials.
- Run the app on `main`
- Sign …
=> Show stored username in General preference pane even when we don't have a valid session

Xcodes.xcodeproj/project.pbxproj, Xcodes.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Xcodes/Frontend/Preferences/AdvancedPreferencePane.swift, Xcodes/Frontend/Preferences/GeneralPreferencePane.swift, Xcodes/Frontend/Preferences/PreferencesView.swift, Xcodes/Frontend/Preferences/UpdatesPreferencePane.swift, Xcodes/Resources/Licenses.rtf, Xcodes/XcodesApp.swift
Fixes #88 
Uses SwiftUI's Settings Scene - https://developer.apple.com/documentation/swiftui/settings Instead of PreferencesWindowController that comes with the `Preferences` add in.
Preferences dependency has been removed. Converted the style with a `PreferencesGroupBoxStyle`, which turned out pretty well. 
Did a quick test for the options and things seems to work. Some awkwardness with InstallHelper as it closes the preferences window automatically, but it works.
The only annoyance that I couldn't figure out is the advanced view looks to have a different background color, compared to the other views, but I couldn't figure out why.
=> Updates PreferencesView To use built in Settings Scene

README.md
A Cask for Xcodes.app [was added](https://github.com/Homebrew/homebrew-cask/pull/99034), and this adds instructions for installing with Homebrew to the README.md.
Closes #65
=> Add Homebrew Cask install instructions

Xcodes/Backend/AppState+Update.swift, Xcodes/Backend/AppState.swift, Xcodes/Backend/Version+Xcode.swift, Xcodes/Backend/Version+XcodeReleases.swift, Xcodes/Backend/Xcode.swift, Xcodes/Frontend/XcodeList/InfoPane.swift, Xcodes/Frontend/XcodeList/XcodeListView.swift, Xcodes/Frontend/XcodeList/XcodeListViewRow.swift, XcodesTests/AppStateUpdateTests.swift
This change attempts to improve how different versions with the exact same build identifier are represented in the UI.
Background: Sometimes the last prerelease version (for example 12.4 Release Candidate) and the release version (12.4) are the exact same and have the same build identifier as a result (12D4e in this case.) While we _could_ just do the easy thing and have independent rows in the list for each version, this makes it difficult to determine which versions are installed. I also doubt that anyone would really want more than one version installed when they're the exact same build. If anything, most users would want to know when they're the exact same so that they can _avoid_ installing another version.
Through version 1.0.3 (4) I'd attempted to handle this by filtering out …
=> Improve how identical builds are represented in the UI

Xcodes/Frontend/MainWindow.swift
When the info pane was simply hidden, the split view would still allow you to resize the remaining split (note the cursor in the first recording), which resulted in weird behaviour. Instead, just remove the info pane split and then the split view doesn't let you resize. Had to move where the global "cancel install" alert is in the view hierarchy as a result, because it might have to be presented even if the info pane isn't part of the view hierarchy.
I tried changing the alert so it wasn't a part of the main window at all, and was instead local to the buttons that triggered its presentation, and this worked for all but the case where the CancelInstallButton was used from the Xcode menu. So for now I left it close to where it already was.
Before: …
=> Remove info pane from split view instead of hiding it

Xcodes/Frontend/Common/ObservingProgressIndicator.swift, Xcodes/Frontend/XcodeList/InstallationStepView.swift
Fixes #93 
Move the `.help` away from the StepView into the ProgressIndicator so that it can catch the fraction completed events.
=> Moves the .help for the ProgressIndicator so it refreshes with the fraction change

.github/release-drafter.yml, README.md
This template is used by Release Drafter to update the GitHub release notes automatically. Having these instructions here is valuable for users who are linked to a release and may not already know how to install the release.
=> Add install and update instructions to release notes

Xcodes/Backend/AppState+Install.swift, Xcodes/Backend/AppState+Update.swift, Xcodes/Backend/AppState.swift, Xcodes/Frontend/Preferences/UpdatesPreferencePane.swift
Whenever the available Xcodes gets update, check to see if the user wants to auto install it. If so, do it.
Inside of Preferences > Updates, there is an option to auto install the latest xcode version or the latest beta version. 
I also added in a Timer that runs every 6 hours. This is to get around that if the user has the app open, but never goes back into it, it should still try and update. I've updated the auto refresh check to every 5 hours before it's invalid.
____
Closes #99
=> Auto Install Xcode if wanted

Xcodes/AppleAPI/Sources/AppleAPI/Client.swift, Xcodes/Backend/AppState.swift, Xcodes/Frontend/MainWindow.swift, Xcodes/Frontend/SignIn/SignInCredentialsView.swift
- Removed the functionality where authentication errors would present an alert
- Added an inline error message to the sign in view for authentication errors
- Handle the case where authentication responds with an account locked error
- From an unauthenticated state open up the sign in view either from preferences or the icon in the menu bar
- Fill in your username but provide an incorrect password
- You should see an inline error message "Invalid username and password combination"
- Tapping cancel or next should clear this error message
- If you input a username that is common/short/not an email address like "test" the app will now show a proper error message for account locked. Previously this would generate an alert of the form "Received an unexpected sign in response."
=> Show sign in errors inline on sign in view

Xcodes.xcodeproj/project.pbxproj, Xcodes/AppleAPI/Sources/AppleAPI/Client.swift, Xcodes/Backend/AppState.swift, Xcodes/Frontend/Common/XcodesSheet.swift, Xcodes/Frontend/MainWindow.swift, Xcodes/Frontend/Preferences/GeneralPreferencePane.swift, Xcodes/Frontend/SignIn/SignInCredentialsView.swift, Xcodes/Frontend/SignIn/SignedInView.swift, Xcodes/Frontend/XcodeList/MainToolbar.swift
- Closes #22. If login is required by an action such as tapping Install on one of the Xcode versions the user will be prompted with a login view rather than an error alert.
- Added a login button to the main toolbar
- Launch the app starting from a state where you are not logged in 
- Tap the person icon in the main toolbar and verify you are presented with the login view
- Close the login view for now without signing in
- Tap Install on an Xcode version you currently don't have installed
- You should be prompted with a login sheet
- After signing in the install should continue as normal (An exception to this is if you get challenged by 2FA then the download may not happen automatically. Maybe we want to track this as a separate bug?)
- After successful login you can tap the person icon …
=> Handle required log in scenarios better instead of showing errors

Xcodes.xcodeproj/project.pbxproj, Xcodes/Backend/AppState+Install.swift, Xcodes/Backend/AppState+Update.swift, Xcodes/Backend/AppState.swift, Xcodes/Backend/XcodeCommands.swift, Xcodes/Frontend/Common/XcodesAlert.swift, Xcodes/Frontend/MainWindow.swift, Xcodes/Frontend/XcodeList/XcodeListViewRow.swift
Closes #128 
Refactored how alerts are presented so its not possible to present multiple alerts at once. The previous implementation using overlays was causing an alert to be displayed anytime the parent view got refreshed.
One interesting way to test this is to change the Run configuration from Debug to Test (in Edit Scheme). This will cause an issue where privelidged helper cannot install.
- Running a build using Test you can then try and switch Xcode versions either with the checkmark icon in the list, or using "Make active" button in the info panel when an installed version of Xcode is selected.
- After tapping Install and providing account credentials to the helper you will see an error alert 
- Dismiss this alert and you should no longer see a duplicate error alert pop up
=> only present a single alert at time

Xcodes/Backend/AppState.swift, Xcodes/Backend/Xcode.swift, Xcodes/Frontend/InfoPane/InfoPane.swift
Adds the release date if known to the Info Pane for each Xcode release.
- Adds optional release date property to `Xcode` struct populated from `AvailableXcode.releaseDate`
- Uses existing `DateFormatter` to display release date in the Info Pane
- Currently placed below "Release Notes" link and above "Compatibility" section, I'm open to suggestions on better ordering
Issue: #145 
Preview screenshot to show placement and formatting of release date
=> Enhancement: Add Xcode release date to info pane in Xcodes.app

Xcodes/AppleAPI/Sources/AppleAPI/Client.swift, Xcodes/Backend/AppState+Update.swift, Xcodes/Backend/AppState.swift, Xcodes/Backend/Downloads.swift, Xcodes/Resources/Licenses.rtf, XcodesTests/AppStateTests.swift
Getting a better understanding of the different api results from different types of Apple ID's
- Non-Developer AppleID: Gives back a `Session.provider == null`, resultCode on listDownload != 0
- Non-Paid Apple Developer: Gives back `Session.provider == null`, resultCode == 0 (Allowing to download versions)
- Full paid Developer: Session.provider == "Something"
This fixes point 2 where Xcodes will now allow Non-Paid Apple developers to download Xcode versions as they should be able to.
=> Allow Non-Paid Apple Developer to download versions.

Xcodes/Backend/DateFormatter+.swift
Fixes: #190 
As discussed in #190, there seem to be some regions and combinations of 24-hour time preference that cause return unexpected results for the date formatter used when parsing API responses.
With an region such as `en-GB` selected on a machine under System Preferences > Language and Region, and 24-hour unchecked, when using a date formatter with the string `"MM/dd/yy HH:mm"` it will actually return a string that includes the am/pm
Use a fixed locale of `"en_US_POSIX"` for date parsing of api responses.
- Go to System Preferences > Language and Region on your machine
- Select Region: Europe > United Kingdom
- Uncheck `24-Hour Time`
- Launch the Xcodes app
- Try and download any Xcode version that you do not currently have installed on your machine
- Another thing to test is …
=> Use a fixed locale for API response date parsing

Xcodes/AcknowledgementsGenerator/Package.swift, Xcodes/Backend/AppState+Install.swift, Xcodes/Backend/AppState.swift, Xcodes/Backend/Path+.swift, Xcodes/Backend/XcodeCommands.swift, Xcodes/Frontend/XcodeList/XcodeListViewRow.swift
As discussed in [#183](https://github.com/RobotsAndPencils/XcodesApp/issues/183) and [#183](https://github.com/RobotsAndPencils/XcodesApp/issues/110) there are sometimes dependencies that are specifically looking for `Xcodes.app` instead of using the currently selected Xcode. A workaround is by creating a symbolic link to whichever Xcode Version you'd like, but naming it `Xcode.app` 
And example from the commandline: 
```
% ln -s /Applications/Xcode-13.3.0.app /Applications/Xcode.app
```
I don't use symbolic links all that much, but hopefully this covers the basis. An enhancement on top of this could be the ability to update the symbolic link when a user selects a version (by preference only) 
Also refactored that anywhere we had hardcoded the `Applications` directory to look at …
=> Adds option to create symbolic link at Path Xcode.app

Xcodes.xcodeproj/project.pbxproj, Xcodes/Backend/AppState+Install.swift, Xcodes/Backend/AppState.swift, Xcodes/Backend/Collection+.swift, Xcodes/Backend/XcodeCommands.swift, Xcodes/Frontend/Common/XcodesAlert.swift, Xcodes/Frontend/MainWindow.swift, Xcodes/Frontend/XcodeList/XcodeListViewRow.swift
When installing Xcode, lots of time a user does not have min MacOS version that is needed to run that particular version. 
The PR will check the minimum required OS version what the user is currently running and if the Xcode version is higher, will prompt to double check they want to install it. User can always install it if they want.
(Ignore the invalid versions on the prompt, pasted for clarification)
Basic test is change the check in `AppState.checkMinVersionAndInstall` removing the `!`
```swift 
// from
if !ProcessInfo.processInfo.isOperatingSystemAtLeast(xcodeMinimumMacOSVersion) {
// to
if ProcessInfo.processInfo.isOperatingSystemAtLeast(xcodeMinimumMacOSVersion) {
```
That will always prompt the user on install. 
Closes #184
=> Add check for min MacOS version when installing

Xcodes/Backend/AppState.swift, Xcodes/Frontend/Preferences/AdvancedPreferencePane.swift
Adds an option to Advance Preferences to automatically update the Symbolic Link for Xcodes.app to whatever Xcode version you've selected. 
Closes #180
=> Add Preference to make Symbolic Link Automatic on Xcode Select

Xcodes/Backend/AppState.swift
Fixes #202 
App did not load the create symlink preference on start, and therefore showed the incorrect option on the preferences.
=> Fix: Load create SymLink preference on start

Xcodes/Resources/en.lproj/Localizable.strings
From the localization updates in #203 there were some format's using `%@` instead of `%d` for when we need an int.
=> Fixes some localization formatting from string to ints

Xcodes.xcodeproj/project.pbxproj, Xcodes.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Xcodes/Frontend/Preferences/PreferencesView.swift, Xcodes/Frontend/Preferences/UpdatesPreferencePane.swift, Xcodes/Resources/Licenses.rtf, Xcodes/XcodesApp.swift
Updates Sparkle to 2.1. 
Major update, so had some refactoring as long as was the Sparkle singleton flow. 
Passes up a new environment Object to use in the Update Preferences pane so it shares the one Updater.  
To Test:
- Run app and try and check for updates. 
- Change version to a lower version + build, check for updates. Sparkle should prompt for new version.
=> Update Sparkle to 2.1

Xcodes/Frontend/MainWindow.swift
Fixes #244 
The localization for the minimum supported version alert wasn't showing properly
Before:
After (faking it out):
=> Fix minimum version supported localization alert message

Xcodes/Frontend/InfoPane/InfoPane.swift
Thanks to localized by community, we found some incorrect date format localization. https://github.com/RobotsAndPencils/XcodesApp/pull/249#issuecomment-1152891477
Before:
After:
=> Update Release Date format on InfoPane for better localization

Xcodes/Backend/AppState.swift, Xcodes/Backend/XcodeCommands.swift, Xcodes/Frontend/InfoPane/InfoPane.swift, Xcodes/Resources/de.lproj/Localizable.strings, Xcodes/Resources/en.lproj/Localizable.strings, Xcodes/Resources/es.lproj/Localizable.strings, Xcodes/Resources/fr.lproj/Localizable.strings, Xcodes/Resources/hi.lproj/Localizable.strings, Xcodes/Resources/it.lproj/Localizable.strings, Xcodes/Resources/ja.lproj/Localizable.strings, Xcodes/Resources/ko.lproj/Localizable.strings, Xcodes/Resources/ru.lproj/Localizable.strings, Xcodes/Resources/tr.lproj/Localizable.strings, Xcodes/Resources/zh-Hans.lproj/Localizable.strings, Xcodes/Resources/zh-Hant.lproj/Localizable.strings
Added the ability to copy the URL of release notes by right-clicking on it.
=> Adds Copy Release Notes URL context menu

Xcodes/Frontend/Common/ObservingProgressIndicator.swift
Hi,
This is a really minor change to use monospaced digits for the download progress (X.X GB of Y.Y GB), which prevents the label from jumping around so much when the numbers change.
Thanks!
=> Use monospaced digit font for download progress

Xcodes/Frontend/Preferences/AdvancedPreferencePane.swift, Xcodes/Frontend/Preferences/ExperiementsPreferencePane.swift, Xcodes/Frontend/Preferences/GeneralPreferencePane.swift, Xcodes/Frontend/Preferences/PreferencesView.swift, Xcodes/Frontend/Preferences/UpdatesPreferencePane.swift
Fixes #242.
This PR fixes a SwiftUI related crash on macOS Ventura (both beta1 and 2) when users enter the `Advanced` settings tab and then navigate to another tab.
This crash can be solved by moving pane `.frame(width:)` to its parents. I know it's tricky, but it should solve this issue.
=> Fix macOS Ventura crash on Settings View 

Xcodes.xcodeproj/project.pbxproj, Xcodes/Backend/AppState.swift, Xcodes/Backend/Entry+.swift, Xcodes/Backend/Environment.swift, Xcodes/Backend/SelectedActionType.swift, Xcodes/Frontend/Preferences/AdvancedPreferencePane.swift, Xcodes/Resources/en.lproj/Localizable.strings
Fixes #180 
This will add the option on Activate/Select to rename it to `Xcode.app`. 
Users will now get 2 options for the  Activate/Select
- Default (save as `Xcode-x.x.x.app`)
- Rename Active to `Xcode.app`. 
When the latter is chosen, the user cannot select the `Create Symbolic Link`. Xcodes will try to do its best to rename the old named `Xcodes.app` to the version number (default) format.
=> add option to rename Xcode to Xcode.app on select.

Xcodes/Backend/AppState.swift, Xcodes/Backend/Path+.swift, Xcodes/Frontend/Preferences/AdvancedPreferencePane.swift, Xcodes/Resources/en.lproj/Localizable.strings
Closes #8 
Closes #148 
This will allow a user to change their installation directory. After Xcodes downloads and extracts, it will copy the new file to this directory as well as changing the installation directory will also change the search directory.  Default is always `/Applications`
I'm not 100% certain if changing the install directory will mess up any other apps or services that perhaps look at the `/applications` directory.
=> Ability to change the installation directory

Xcodes/Resources/tr.lproj/Localizable.strings
It's suggested to update the app to 1.7.1 to fix the missing Turkish translation strings.
=> Added Turkish missing translations in 1.7.0

Xcodes/Resources/fr.lproj/Localizable.strings
Hi! 👋
This PR is splitted into 2 commits:
*  translation fixes (probably required)
* translation updates (suggested)
So yes, it can be discussed if required. 😁
For update, an explanation has been added for each case.
A French translation of Git repository is "dépôt". The [French version of Git documentation](https://git-scm.com/docs/git-checkout/fr) uses this term.
"Expérience" is not forever a risk, while "Expérimentation" includes a potential risk.
Apple uses "SMS" instead of "texto".
"(Pré-)requis" is [preferred](https://developer.apple.com/fr/support/xcode/) to "Exigences".
"décompression", "décompressé" is more [commonly used](https://support.apple.com/fr-fr/guide/mac-help/mchlp2528/mac) than "extraction", "agrandie" or "désarchivage".
=> Fix French Translation

Xcodes/Backend/AppState+Install.swift, Xcodes/Backend/AppState.swift, Xcodes/Backend/AvailableXcode.swift, Xcodes/Backend/Environment.swift, Xcodes/Backend/URLRequest+Apple.swift
I hate having to log into my Apple Developer account, always having to put in my 2fa code, when I want to download Xcode, but Apple has never given us the ability to do so.
This PR changes that.
By using a public URL provided by Apple, we can get a token cookie that can be used to download the version of Xcode that we wish, without having to provide a log in. 🎉 
Caveats:
- This does not work when using the `Apple` datasource. More specifically that token doesn't work for listing the Xcode versions with `https://developer.apple.com/services-account/QH65B2/downloadws/listDownloads.action`
=> Add ability to download Xcode without logging in using XcodeReleases

Xcodes/Frontend/XcodeList/MainToolbar.swift
Apple have renamed `showPreferencesWindow` to `showSettingsWindow` which was stopping the cog icon from doing anything on Mac OS 13
=> fix: Preference button on toolbar not working on Mac OS 13 Ventura

Xcodes/Backend/AppState+Install.swift, Xcodes/Backend/AppState.swift
In Sept 2022, Xcodes was updated to use the same mechanism that is used to download runtimes with no login, to download Xcode.
ie: https://developerservices2.apple.com/services/download?path=/Developer_Tools/tvOS_16.1_Simulator_Runtime/tvOS_16.1_Simulator_Runtime.dmg returns 200 to set the ADCDownloadAuth cookie to be able to download
As of mid Nov 2022, Apple has return 403 (forbidden) for this endpoint for Xcode versions only. Runtimes still return 200.
https://developerservices2.apple.com/services/download?path=/Developer_Tools/Xcode_14.0.1/Xcode_14.0.1.xip
I'm not sure if this is deliberate from Apple (My guess is it is), but this PR reinstates the old way of download xcodes as all libraries and utilities have done for years now.
I don't think Apple will ever allow this open again. I …
=> Switch Xcode releases back to using Apple Auth :(

Xcodes.xcodeproj/project.pbxproj, Xcodes/Backend/AppState.swift, Xcodes/Backend/Hardware.swift, Xcodes/Backend/XcodeCommands.swift, Xcodes/Frontend/Preferences/AdvancedPreferencePane.swift, Xcodes/Resources/en.lproj/Localizable.strings
Some devs (like myself) don't always get to have the latest and greatest. Sometimes dependencies, take their time updating to support Arm64. In those cases, a trick to make things work is to open Xcode in Rosetta.
This PR shows an option in settings (only available for Apple Silicon machines)
And when turned on, gives the ability to "open" in Rosetta
Closes #321
=> Adds open in Rosetta option for Apple Silicon machines

Xcodes/Frontend/XcodeList/BottomStatusBar.swift, Xcodes/Frontend/XcodeList/MainToolbar.swift
With the update to macOS Ventura a few SwiftUI behaviors have changed. I found 2 things in the UI that worked with Monterey but are now a bit broken. I fixed both issues, but it would be good if someone could test on previous macOS versions!
| Toolbar before fix | Toolbar after fix |
| ------------------ | --------------- |
| <img width="1055" alt="Screenshot 2023-01-16 at 17 46 28" src="https://user-images.githubusercontent.com/42500484/212731685-759bbb29-3dd3-43a7-a35c-6c574ad31c74.png"> | <img width="1055" alt="Screenshot 2023-01-16 at 17 47 18" src="https://user-images.githubusercontent.com/42500484/212731786-06aa4583-e48c-4a11-80d6-db10b0320d48.png"> |
| Status bar before fix | Status bar after fix |
| -------------------- | ------------------- |
| <img width="1055" alt="Screenshot …
=> Ventura UI fixes

Xcodes/Frontend/SignIn/PinCodeTextView.swift, Xcodes/Frontend/SignIn/SignIn2FAView.swift, Xcodes/Frontend/SignIn/SignInSMSView.swift
After entering last character, we need manually click the continue button.
We should follow how Apple is doing for their 2FA Service.
After entering last character, trigger the continue button automatically.
Run the Preview on PinCodeTextView.swift with Xcode 14.3
When entering last character check the "Previews log" console in Xcode.
=> Add PinCodeTextField autocomplete support

.github/workflows/ci.yml, Xcodes.xcodeproj/project.pbxproj, Xcodes.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Xcodes/Backend/AppState+Install.swift, Xcodes/Backend/AppState.swift, Xcodes/Resources/Licenses.rtf
Closes #17
Uses suggested [DockProgress](https://github.com/sindresorhus/DockProgress) to display a progress bar overlay on top of the dock icon as an Xcode is downloading.
Successor to #85. A new `overallProgress` has been pulled up to track the downloading and the unarchive portion of installing an Xcode. Within the `overallProgress` the following weights are applied:
* 90% of the overall progress is allocated to the download
* The remaining 10% is allocated to the unarchive step
* This is tracked in a binary fashion (incomplete or complete) as no progress is provided in any sort of callback during the unarchive process
Below are some previews:
These final steps require user interaction so no new child `Progress` objects were created to track these. However, you can see that once it …
=> Add installation progress bar to dock icon

.github/workflows/ci.yml, Xcodes/Frontend/XcodeList/MainToolbar.swift
This fixes the settings icon on Sonoma so it actually opens settings via the toolbar
Pick a lane Apple!
=> fix: settings link on Sonoma not working

Xcodes.xcodeproj/project.pbxproj, Xcodes/Backend/AppState.swift, Xcodes/Backend/XcodeCommands.swift, Xcodes/Frontend/InfoPane/CompatibilityView.swift, Xcodes/Frontend/InfoPane/CompilersView.swift, Xcodes/Frontend/InfoPane/IconView.swift, Xcodes/Frontend/InfoPane/IdenticalBuildView.swift, Xcodes/Frontend/InfoPane/InfoPane.swift, Xcodes/Frontend/InfoPane/InfoPaneControls.swift, Xcodes/Frontend/InfoPane/InstallationStepDetailView.swift, Xcodes/Frontend/InfoPane/InstalledStateButtons.swift, Xcodes/Frontend/InfoPane/NotInstalledStateButtons.swift, Xcodes/Frontend/InfoPane/NotInstalledStateButtonsView.swift, Xcodes/Frontend/InfoPane/ReleaseDateView.swift, Xcodes/Frontend/InfoPane/ReleaseNotesView.swift, Xcodes/Frontend/InfoPane/SDKsView.swift, Xcodes/Frontend/InfoPane/UnselectedView.swift, Xcodes/Frontend/MainWindow.swift, Xcodes/XcodesApp.swift
1. The preview code is too heavy. It crashes all the time.
2. Explicit dependencies are too broad
- make it hard to create preview data (in reality)
- reduce performance (in theory)
- reduce reusability (in the future)
3. The `body` is too big
- hard to reason
- hard to test by preview
1. I move subviews to separate files
- reduce data dependency
- reduce logic responsibilities, focus mostly on displaying data
- reduce layout responsibilities. Let the outer view decide the layout
- add preview to test locally
2. I fix `InforPane`
- reduce data dependency
- improve preview performance. It is fast and doesn't crash anymore
- fix layout
- I move `UnselectedView` out to:
- `InfoPane` should only care about displaying data, not whether an `Xcode` is selected
- I want to hear from you about …
=> Clean up code in `InfoPane` to be more robust

Xcodes/Backend/XcodeCommands.swift, Xcodes/Frontend/XcodeList/XcodeListViewRow.swift
I noticed that there is often a long delay between clicking Install and the button switching to the linear progress view which sometimes makes it seem unresponsive. So I added a circular style progress view to the install button to indicate activity and reduce the chance of repeat clicks.
Before:
After:
=> Activity Indicator on Install Pressed

Xcodes/AppleAPI/Sources/AppleAPI/Client.swift
If status code 412 comes back for logging in an error is provided regarding Apple Acknowledgements however, the security code entry does not cover this case. This change simply re-uses the existing error to explain why login failed.
closes #331, closes #406, Closes #417,  closes #418, closes #438 closes #440
=> Descriptive error for login status code 412

Xcodes/Frontend/SignIn/SignInPhoneListView.swift
When I only have one trusted phone number and see the number selection view, I often get confused since it is hard to distinguish a tappable section in the list without a row highlight.
This change will select a phone number as a default when only one option exists.
|Single phone number |Multiple phone number |
|-|-|
|<img width="406" alt="Screenshot 2023-12-20 at 0 44 13" src="https://github.com/XcodesOrg/XcodesApp/assets/20346613/e9b00853-76b6-4d60-a614-f56717224bfc">|<img width="406" alt="Screenshot 2023-12-20 at 0 43 32" src="https://github.com/XcodesOrg/XcodesApp/assets/20346613/44707196-a6eb-4322-a111-7a9796d65e68">|
|Single phone number with row selected |Multiple phone number with row selected |
|-|-|
|<img width="406" alt="Screenshot 2023-12-20 at 0 43 06" …
=> Add default phone number selection when there is only one

Xcodes.xcodeproj/project.pbxproj, Xcodes.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Xcodes/Backend/AppState+Install.swift, Xcodes/Backend/AppState+Runtimes.swift, Xcodes/Backend/AppState.swift, Xcodes/Frontend/Common/XcodesAlert.swift, Xcodes/Frontend/InfoPane/InfoPane.swift, Xcodes/Frontend/InfoPane/PlatformsView.swift, Xcodes/Frontend/MainWindow.swift, Xcodes/Frontend/Preferences/PlatformsListView.swift, Xcodes/Frontend/Preferences/PreferencesView.swift, Xcodes/Frontend/XcodeList/XcodeListView.swift, Xcodes/Resources/Licenses.rtf, Xcodes/Resources/Localizable.xcstrings, Xcodes/XcodesApp.swift, Xcodes/XcodesKit/Sources/XcodesKit/Models/Runtimes/CoreSimulatorImage.swift, Xcodes/XcodesKit/Sources/XcodesKit/Models/Runtimes/RuntimeInstallState.swift, Xcodes/XcodesKit/Sources/XcodesKit/Models/Runtimes/RuntimeInstallationStep.swift, Xcodes/XcodesKit/Sources/XcodesKit/Models/Runtimes/Runtimes.swift, Xcodes/XcodesKit/Sources/XcodesKit/Services/RuntimeService.swift, Xcodes/XcodesKit/Sources/XcodesKit/Shell/XcodesShell.swift
Adds a list of the platforms installed on the machine via a side bar button, so a user can easily see all that's installed and delete any they so wish.
| Left Nav | Platforms List |
|--------|--------|
| <img width="469" alt="Screenshot 2024-01-01 at 7 47 08 PM" src="https://github.com/XcodesOrg/XcodesApp/assets/1119565/75145ff9-d3c1-4349-83a5-b68d90ec985f"> | <img width="543" alt="Screenshot 2024-01-01 at 7 47 50 PM" src="https://github.com/XcodesOrg/XcodesApp/assets/1119565/bc466b3a-a9ce-487c-a449-a7762b065407"> | 
Future enhancements could include the ability to know when you have a platform installed (but not the correlated Xcode).
=> Add new Platforms List Window

Xcodes/XcodesApp.swift
The expected alert when choosing to delete a platform was not appearing. If I opened the `PreferencesView` and moved it off to the side I can see the alert appear over it when clicking the delete button. After adding this change I was able to see the alert in the `PlatformsListView`.
=> Handle preference alerts from the PlatformsListView

Xcodes/Frontend/About/AboutView.swift, Xcodes/Frontend/XcodeList/BottomStatusBar.swift, Xcodes/Resources/Localizable.xcstrings
Added the ability to sponsor/donate to Xcodes via the OpenSource Collective https://opencollective.com/xcodesapp
No requirement what so ever!
Closes https://github.com/XcodesOrg/XcodesApp/issues/273
=> Add Sponsor/Donate Button

Xcodes/AcknowledgementsGenerator/Sources/AcknowledgementsGenerator/Tools/Xcode.swift
When reading the output from the defaults command invocation, we need to remove the trailing newline. Otherwise, the path will not resolve correctly.
=> Remove newline from derived data path returned by defaults

Xcodes/Frontend/Common/NavigationSplitViewWrapper.swift, Xcodes/Frontend/MainWindow.swift
Adds back in the left side toggle. Users could drag the left sidebar all the way, hidding it, but there was no way to return it back. 
Closes #498
=> fix: adds back in sidebar toggle button so users don't get stuck

Xcodes/Frontend/InfoPane/CompilersView.swift, Xcodes/Frontend/InfoPane/InfoPane.swift, Xcodes/Frontend/InfoPane/SDKsView.swift
Allows selecting text from:
- Xcode Info header
- Compilers view
- SDKs view
=> Allow selecting text for version info

Xcodes/Resources/Localizable.xcstrings
This is a complete localization for Greek language.
All entries have been cross-checked against the latest official glossary files (AppleGlot) for macOS, in order to seamlessly integrate with familiar systemic terms. Some entries though adapted to more modern technical terms given that the app is primarily used by developers.
Notes:
1. There are some layout issues that need to be addressed. Quite a few labels are very compact and wrap text unnecessarily (imagine that this is a problem in any language that tends to be more verbose than English)
2. There are a few instances that code is trying to match substrings in order to produce clickable links (via attributed string). This is error prone and leads to crashes _if_ the specific entry is untranslated or doesn't include the target …
=> Greek language localization

Xcodes/Resources/Localizable.xcstrings
This PR completes the translation of zh-Hant (100%), unifies the terms (such as '拷貝'), and reviews the current translation.
r? @itszero @toto6038 [done]
=> l10n(zh-Hant): Update translation for 2.0.2

Xcodes/Backend/AppState+Runtimes.swift, Xcodes/Frontend/InfoPane/InfoPane.swift, Xcodes/Frontend/InfoPane/PlatformsView.swift, Xcodes/XcodesKit/Sources/XcodesKit/Models/Runtimes/Runtimes.swift
Fixes issue where iOS 17.4 runtime was not showing on Xcode 15.3
This was because we were grabbing only the first option (naïvely thinking that there would be a singular platform per release) and instead set the `sdkToSimulatorMappings` to an array.
This allows 17.4 to show properly.
=> fix runtime not appearing when multiple runtimes exist for same build

Xcodes/Frontend/SignIn/SignInCredentialsView.swift
Sometimes, we can not type password when we forgot to switch back to English keyboard.
It may related to a focus issue, so I added a `.focused` modifier to resolve the issue.
I think that might because when `SecurityField` gets focus, it automatically switches to English while in process, `SecurityField` loses the focus ( not sure why ). 
By implementing the fix, it works correctly in any situation.
Here is a comparison video for you to checkout what I have resolved.
https://github.com/XcodesOrg/XcodesApp/assets/37542129/ddca0d7b-aec3-40d0-a8c3-1b2cef3e8800
=> Improve signing experience when using non-english keyboard

Xcodes/Resources/Localizable.xcstrings
Hello, 
I have added the German localization for some new values.
=> Updated german localization

Xcodes/Frontend/InfoPane/IconView.swift, Xcodes/Frontend/InfoPane/InfoPane.swift
Replace the default icon in info page.
**Before:**
**After**
=> replace default icon in info page

Xcodes/Frontend/Preferences/DownloadPreferencePane.swift, Xcodes/Frontend/Preferences/ExperiementsPreferencePane.swift, Xcodes/Frontend/SignIn/SignInPhoneListView.swift, Xcodes/Resources/Localizable.xcstrings
The height of AttributedText will change when switch difference tab in preference. 
**Screenshot**
**Solution**
Use Text and markdown format to replace of AttributedText.
=> Replace AttributedText with markdown to fix the layout issues

Xcodes/Frontend/XcodeList/XcodeListView.swift
fixed #537
seems there is a pull request (#535) fixed this bug, but I think this PR is a more reasonable way to have this fixed instead of have a padding less than 8
@MattKiazyk and thanks for the quick responding!
another tip: while I try update the list using `ScrollView` + `LazyVStack` + `ForEach` should be ok compare to using `List` directly, but this will cause more unexpected error like the context menu only triggerred on the text area, so I think may be this  should be an optimization in the future
=> fix: xcode list row text hidden on macOS 14.4

.github/workflows/xcstrings.yml, Xcodes/Resources/Localizable.xcstrings
Adds an action that will check the `localizable.xcstrings` file for any missing translations. Contributors should fix those up with default values so that users don't see `View.header.titlestring` in their language.
=> adds localization validation on PR's 

CONTRIBUTING.md, README.md, Xcodes/Backend/AppState.swift, Xcodes/Resources/Localizable.xcstrings
macOS and GitHub casing changes etc
=> fix: product name casings

Xcodes/Backend/Environment.swift
Swift 5.10 introduces stricter concurrency check which adds one more warning **`Reference to captured var 'progress' in concurrently-executing code; this is an error in Swift 6`**.
Because progress update is based on Notification and **operates on `OperationQueue.main`**, so we don't need to worry about data races.
So I opt-out concurrency check here by using `nonisolated(unsafe)`
=> Resolve concurrency check warning on Swift 5.10

Xcodes/Frontend/InfoPane/InfoPane.swift, Xcodes/Frontend/InfoPane/InfoPaneControls.swift
- Achieves left aligning the "Unarchiving" pane for a nicer look, or any step, as well as making the close button appear in the same spot as a side effect.
- Make some previews wider for better previewing
| Prior Step (reference)  | Before | After |
| ------------- | ------------- | ------------- |
| <img width="391" alt="Screenshot 2024-05-28 at 11 45 49 AM" src="https://github.com/XcodesOrg/XcodesApp/assets/20747774/eeffd321-a243-4ec7-94f8-9d6b32632488">  | <img width="395" alt="Screenshot 2024-05-28 at 11 45 39 AM" src="https://github.com/XcodesOrg/XcodesApp/assets/20747774/314b1725-0a5a-408d-8857-a553aa8fbf40"> | <img width="403" alt="Screenshot 2024-05-28 at 11 45 20 AM" src="https://github.com/XcodesOrg/XcodesApp/assets/20747774/a258c490-6692-4c9a-b604-c613fd901e12"> |
=> Left Align Unarchiving Pane

Xcodes/XcodesApp.swift
Tiny fix in help menu to use updated GitHub URLs. Changed "https://github.com/RobotsAndPencils/XcodesApp" to "https://github.com/XcodesOrg/XcodesApp"
Will solve issue #580
=> fix: Update GitHub URLs in help menu

Xcodes/Backend/AppState+Runtimes.swift, Xcodes/XcodesKit/Sources/XcodesKit/Models/Runtimes/Runtimes.swift, Xcodes/XcodesKit/Sources/XcodesKit/Services/RuntimeService.swift
Supports newer plist from Apple where CryptexDiskImage for iOS 18 runtimes are new and don't include a source url
Give better error messages when downloading iOS 18
=> Fix runtime downloading

Xcodes/Backend/AppState.swift, Xcodes/Backend/XcodeCommands.swift, Xcodes/Frontend/InfoPane/InstallationStepDetailView.swift, Xcodes/Frontend/XcodeList/InstallationStepRowView.swift, Xcodes/Resources/Localizable.xcstrings, Xcodes/XcodesKit/Sources/XcodesKit/Models/XcodeInstallationStep.swift
Fixes #551 
Thanks for creating this awesome app!
This PR aims to fix a minor issue where it keeps displaying the indicator on the install button on error.
To fix it, this PR introduces `authenticating` state to the `XcodeInstallationStep` and makes it to the `installing` state once "INSTALL" button is clicked.
https://github.com/user-attachments/assets/12efaa2d-51ef-42ff-8fb4-5d0035f61c14
https://github.com/user-attachments/assets/ad397f66-0f9b-43ca-bc82-c36e9c6b2b4d
=> Add `authenticating` to the `XcodeInstallationStep`

Xcodes/Backend/AppState+Runtimes.swift, Xcodes/Backend/Environment.swift, Xcodes/Backend/Progress+.swift, Xcodes/Frontend/Common/ObservingProgressIndicator.swift, Xcodes/Frontend/Common/ProgressIndicator.swift, Xcodes/Frontend/InfoPane/RuntimeInstallationStepDetailView.swift
fixes #618 fixes #575 Fixes #571 
Since iOS 18, Apple has switched how runtimes are downloaded. They no longer fully support downloading direct from their website (at least automatically via their runtime source list), and instead use cryptex images. 
With Xcode 16.1 beta 3, `xcodebuild` [now supports downloading runtimes by individual versions](https://developer.apple.com/documentation/xcode-release-notes/xcode-16_1-release-notes#New-Features). Previously you could only download the current runtime for a selected Xcode, which for Xcodes isn't the point.
This PR hooks all that up by using the `xcodebuild -downloadPlatform iOS -buildVersion 22B5045f` type of command to download the runtime as well as install it. The obvious downside of using this way, is we no longer get to use `aria2` for …
=> feat: support downloading of cryptex (ex iOS 18+) runtimes

Xcodes/Backend/XcodeCommands.swift
This gives more clarity to the button intent and better matches other types of context menus.
=> Update label for Cancel Install Button

Xcodes.xcodeproj/project.pbxproj, Xcodes.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Xcodes/AppleAPI/Sources/AppleAPI/Client.swift, Xcodes/AppleAPI/Sources/AppleAPI/URLRequest+Apple.swift, Xcodes/Backend/AppState.swift, Xcodes/Frontend/Common/XcodesSheet.swift, Xcodes/Frontend/MainWindow.swift, Xcodes/Frontend/SignIn/SignIn2FAView.swift, Xcodes/Frontend/SignIn/SignInPhoneListView.swift, Xcodes/Frontend/SignIn/SignInSMSView.swift, Xcodes/Frontend/SignIn/SignInSecurityKeyPinView.swift, Xcodes/Frontend/SignIn/SignInSecurityKeyTouchView.swift, Xcodes/Resources/Licenses.rtf, Xcodes/Resources/Localizable.xcstrings
Fixes #357, Fixes #439, Fixes #578, Fixes #549, Fixes #411
Currently, if a user of the app tries to sign in with an Apple ID that uses physical security keys as a 2nd-factor, the auth flow will fail as this is currently unsupported 
As physical security keys are a security improvement on SMS based 2FA, we should support this to allow use of Xcodes without compromising their Apple ID account security. There are also many open issues currently requesting this functionality (linked in the top) 
This PR modifies the auth flow, to detect when a security key challenge is issued, prompt the user to use their security key, and uses libfido2 to create an assertion on the challenge and sends it back to Apple
Apple uses the standard [WebAuthn flow](https://www.w3.org/TR/webauthn-2/) to add and …
=> Implement Security Key Auth 

Xcodes/Resources/Localizable.xcstrings
Add zh_Hans translation for "Installed Platforms".
Fix Greek translation for "Enter the %1$d digit code sent to %2$@". 
The wrong translation has "%1$d" written as "%2$d". This causes the compilation to fail using Xcode 16.
=> Fix one Greek localization. Add one zh_Hans localization.

Xcodes/Resources/Localizable.xcstrings
This PR updates a untranslated string in this UI:
r? @itszero
=> Update translation in zh-Hant

Xcodes/Resources/Localizable.xcstrings
- Added all missing strings;
- Removed preposition from "Updated at" date string in localized version.
=> Update Localizable.xcstrings for Russian language (3)

Xcodes/Backend/AppState+Install.swift, Xcodes/Backend/AppState+Runtimes.swift, Xcodes/Backend/AppState.swift, Xcodes/Backend/DataSource.swift, Xcodes/Backend/Downloader.swift, Xcodes/Frontend/Preferences/AdvancedPreferencePane.swift, Xcodes/Frontend/Preferences/DownloadPreferencePane.swift, Xcodes/Frontend/Preferences/ExperiementsPreferencePane.swift, Xcodes/Frontend/Preferences/UpdatesPreferencePane.swift, Xcodes/Frontend/XcodeList/MainToolbar.swift, Xcodes/Frontend/XcodeList/XcodeListCategory.swift
- Define enumerations for preferences that can be managed in an enterprise environment using MDM
- Add methods in AppState to check for managed preferences
- Update Advanced, Download, Experiments and Update preference pane to disable controls to modify any of the managed preferences
=> Disallow changes to managed preferences

Xcodes/Backend/AppState.swift, Xcodes/Frontend/XcodeList/BottomStatusBar.swift, Xcodes/Frontend/XcodeList/XcodeListView.swift
- Introduced a new preference keys allowedMajorVersions, hideSupportXcodes
- allowedMajorVersions defaults to Int.max (ie allow all versions till date)
- allowedMajorVersions is used to limit the number of major versions to as many as value set for this key. Eg: A value of 1 would allow the latest GA version and one major version before A value of 0 would allow only the latest GA version A value of 2 would allow the latest GA and previous two major versions
- allowedMajorVersions does not have preference UI $ defaults write com.xcodesorg.xcodesapp allowedMajorVersions 2 #to limit to current GA and previous major $ defaults delete com.xcodesorg.xcodesapp allowedMajorVersions  #to remove limits
- Display buildNumber in bottom status bar
=> Add preference keys for 'Restrict allowed versions' & hide 'Support Xcodes'

Xcodes/AppleAPI/Sources/AppleAPI/Client.swift
Apple IDs with "old" passwords (ie those set before a certain date, the cutoff for which I'm not 100% certain) use the `s2k_fo` protocol rather than `s2k`. This legacy protocol involved an extra step in the SRP handshake, where the password was hex-encoded before performing PBKDF2 to derive the shared secret. Luckily it's pretty trivial for us to handle this and fix the erroneous "incorrect username or password" errors that it resulted in.
Closes #644 — this is in fact the root cause behind that issue.
=> Fix handling of s2k_fo

.github/workflows/ci.yml, Xcodes.xcodeproj/project.pbxproj, Xcodes/Frontend/Common/TagView.swift, Xcodes/Frontend/InfoPane/InfoPane.swift, Xcodes/Frontend/InfoPane/PlatformsView.swift, Xcodes/Frontend/InfoPane/RuntimeArchitecture.swift, Xcodes/Frontend/XcodeList/BottomStatusBar.swift, Xcodes/Resources/Licenses.rtf, Xcodes/Resources/Localizable.xcstrings, Xcodes/XcodesKit/Sources/XcodesKit/Models/Runtimes/Runtimes.swift
Starting in Xcode 26 beta 2, Apple is now returning different runtime builds for different architectures. 
This adds support for showing those properly 🎉 
Closes #724
=> Support Xcode 26 multiple Architectures

Xcodes/Frontend/InfoPane/PlatformsView.swift, Xcodes/Frontend/XcodeList/MainToolbar.swift, Xcodes/XcodesKit/Sources/XcodesKit/Models/XcodeReleases/Architecture.swift
Filter controls should be compact in toolbar since the smaller room, and could be larger inside the app
Check out the new UX here
https://github.com/user-attachments/assets/6f6514da-0c2f-4acc-85b1-7b0f32585a01
https://github.com/user-attachments/assets/736d41ce-1292-400b-abb3-1fe76666d406
=> Improve filtering UI/UX on Xcode List

Scripts/fix_libfido2_framework.sh, Xcodes.xcodeproj/project.pbxproj, Xcodes/Backend/AppState+Runtimes.swift
To install Apple Silicon runtimes, users will need to have Xcode 26+ selected in order to use the new architecture variant option on xcodebuild. 
This fixes the check as Xcode 26 RC wasn't doing the proper check. Simpler just to say anything over Xcode 25
=> fix: xcode 26 check for Apple Silicon installs
