README.md

For #70 we would want a better optimal solution that can move it on behalf of the user, but for `v1` , this updates the readme instructions.

Updates readme for install instructions about moving directories

---

Xcodes/Backend/AppState+Install.swift
Xcodes/Backend/AppState.swift
Xcodes/Resources/Licenses.rtf

Fixes #101 
The install command was hardcoded to .aria2, not using the preferences option that is saved in userDefaults. 
Chose urlSession if there is no key.

When downloading, use the downloader from userdefaults

---

Xcodes/Resources/Licenses.rtf

AcknowledgementsGenerator has detected updates to the Sparkle license. These changes are automatically applied using this tool.

include updates to sparkle license

---

.github/workflows/ci.yml

Updates developer dir on CI runs to xcode 12.5

---

Xcodes/Frontend/MainWindow.swift
Xcodes/Frontend/XcodeList/MainToolbar.swift
Xcodes/Frontend/XcodeList/XcodeListCategory.swift
Xcodes/Frontend/XcodeList/XcodeListView.swift

Add new filter for Release or Beta versions

---

Xcodes/AppleAPI/Sources/AppleAPI/Client.swift

Fix #164, show a message when user is not authorized instead of json decoding error.

Show a message when user is not authorized yet

---

Xcodes.xcodeproj/project.pbxproj
Xcodes/Resources/es.lproj/Localizable.strings

- Localizable ES file added.
- Localizing all strings.

Spanish Localization

---

Xcodes.xcodeproj/project.pbxproj
Xcodes/Resources/hi.lproj/Localizable.strings

- Added Hindi Localization File
- Localized all strings except few words left in English for better understanding.

Hindi Localization

---

Xcodes.xcodeproj/project.pbxproj
Xcodes/Resources/ko.lproj/Localizable.strings

- Added Korean Localization File
- Choose Scheme (Xcodes) > Edit Scheme
- Select Run tab > Options
- Set app language to Korean
- Run the app

Add Korean Localization

---

Xcodes.xcodeproj/project.pbxproj
Xcodes/Resources/zh-Hant.lproj/Localizable.strings

Picking up where @ethanhuang13 is left. Here's the full translation for Traditional Chinese.
cc @pofat

Add Traditional Chinese localization

---

Xcodes.xcodeproj/project.pbxproj
Xcodes/Resources/de.lproj/Localizable.strings

Added de.lproj folder containing Localizable.strings with German translation. No changes to Xcode's project file. First translation and github pull request for me, so I hope everything's alright. Cheers.

German translation added

---

Xcodes.xcodeproj/project.pbxproj
Xcodes/Resources/fi.lproj/Localizable.strings

Add Finnish localization

---

Xcodes/Backend/AppState.swift
Xcodes/Frontend/Common/XcodesSheet.swift
Xcodes/Frontend/MainWindow.swift

Fix crash on sign in sheet cancel

---

Xcodes/Resources/zh-Hans.lproj/Localizable.strings

Update zh_Hans localization file with new strings.

Update zh_Hans localizations.

---

README.md

Hi @MattKiazyk , 
Thanks for adding localization contributors section recently. In Traditional Chinese localization, the flag is wrong. So, I change the flag into 🇹🇼 for Traditional Chinese.

Update readme with Taiwan flag

---

Xcodes/Resources/ja.lproj/Localizable.strings

「アーカイブしています」 means 「**now** archiving」

Fix "Unarchiving" localization in Japanese

---

Xcodes/Resources/de.lproj/Localizable.strings

German translation added for install and renaming features

updated German translation

---

Xcodes/Resources/de.lproj/Localizable.strings

Typo in German Localization File

---

README.md
Xcodes.xcodeproj/project.pbxproj
Xcodes/Resources/nl.lproj/Localizable.strings

This adds the Dutch translations for the wonderful Xcodes app!

Add Dutch localization

---

.gitignore
Xcodes/Backend/AppState.swift
Xcodes/Backend/XcodeCommands.swift
Xcodes/Frontend/XcodeList/XcodeListViewRow.swift
Xcodes/Resources/de.lproj/Localizable.strings
Xcodes/Resources/en.lproj/Localizable.strings
Xcodes/Resources/es.lproj/Localizable.strings
Xcodes/Resources/fi.lproj/Localizable.strings
Xcodes/Resources/fr.lproj/Localizable.strings
Xcodes/Resources/hi.lproj/Localizable.strings
Xcodes/Resources/it.lproj/Localizable.strings
Xcodes/Resources/ja.lproj/Localizable.strings
Xcodes/Resources/ko.lproj/Localizable.strings
Xcodes/Resources/ru.lproj/Localizable.strings
Xcodes/Resources/tr.lproj/Localizable.strings
Xcodes/Resources/uk.lproj/Localizable.strings
Xcodes/Resources/zh-Hans.lproj/Localizable.strings
Xcodes/Resources/zh-Hant.lproj/Localizable.strings

resolves #281 
- adding .idea to .gitignore for convenience
- adding option to create Xcode-Beta.app for prerelease Items

Adds an option to save beta versions with `-beta` symlink

---

Xcodes/Resources/es.lproj/Localizable.strings

I've not added all the missing ones but this fills some of them in, including some corrections

Improve Spanish localization in Preferences

---

Xcodes/Resources/tr.lproj/Localizable.strings

Also synced the spaces to be the same line as the base language file(easier to follow lines side by side).

Turkish Localization Update

---

Xcodes/Resources/zh-Hans.lproj/Localizable.strings

Fix zh_Hans localizations

---

README.md
Xcodes.xcodeproj/project.pbxproj
Xcodes/Resources/pl.lproj/Localizable.strings

Hi, I decided to add a Polish translation, I hope you will find it useful.
Thanks for creating such a great tool 🚀

Introduce Polish translations

---

Xcodes/Resources/pt-BR.lproj/Localizable.strings

Hi,
This not only fixes issue #377 but also adds translation for some strings that were missing
Thanks for creating this tool!

Improve Brazilian Portuguese translation

---

Xcodes/Resources/zh-Hans.lproj/Localizable.strings

Including:
ShowOpenInRosetta
ShowOpenInRosettaDescription
Alert.Uninstall.Error.Message.FileNotFound

Update zh_CN localizations.

---

Xcodes.xcodeproj/project.pbxproj
Xcodes.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Xcodes/Frontend/InfoPane/InfoPane.swift

Xcode 15 beta 2 now supports visionOS SDK.

SDK column in the info panel supports displaying visionOS

---

Xcodes/Resources/Localizable.xcstrings

Updated the Turkish translation to 100% after String Catalog Conversion

Updated Turkish to 100%

---

Xcodes.xcodeproj/project.pbxproj
Xcodes.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Xcodes/Frontend/Preferences/UpdatesPreferencePane.swift
Xcodes/Resources/Licenses.rtf

Updates Sparkle to 2.5.2
A few minor updates with the new version, but will allow us to use new features in the future

update Sparkle to 2.5.2

---

Xcodes/Resources/Localizable.xcstrings

Hello there!
This is an incremental localization update for the latest Xcodes version
It includes:
- Localization for new values
- Update for existing values to ensure uniformity of names across all values
- Update for existing values to resolve some visual issues
- Typo fixes
- Meaning fixes / Clearer explanations

Update Ukrainian localisation

---

Xcodes/Frontend/About/AcknowledgementsView.swift
Xcodes/Frontend/Preferences/AdvancedPreferencePane.swift
Xcodes/Frontend/Preferences/DownloadPreferencePane.swift
Xcodes/Frontend/Preferences/ExperiementsPreferencePane.swift
Xcodes/Frontend/Preferences/GeneralPreferencePane.swift
Xcodes/Frontend/Preferences/PreferencesView.swift
Xcodes/Frontend/Preferences/UpdatesPreferencePane.swift
Xcodes/Resources/Localizable.xcstrings

Here is a detailed list of the changes made:
- Settings window width changed from **500**pts to **600**pts in order to better handle longer labels (more apparent to more verbose localizations).
- Subtitles are now colored with secondary system color in order to provide visual hierarchy (Apple is also doing this in their Settings screens)
- Some spacing & padding issues are corrected (see below for comparison)
---
Before             |  After
:-------------------------:|:-------------------------:
Before             |  After
:-------------------------:|:-------------------------:
Before             |  After
:-------------------------:|:-------------------------:
Before             |  After
:-------------------------:|:-------------------------:

Improvements in the layout of the Settings window

---

Xcodes.xcodeproj/project.pbxproj
Xcodes.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Xcodes/Backend/AppState+Install.swift

Fix broken DockProgress Bar

---

Xcodes.xcodeproj/project.pbxproj
Xcodes/Resources/Localizable.xcstrings

Hello I Added Arabic Language to Your app 
Thanks
@MattKiazyk  please review

ADD: Added Arabic Localizations To Xcodes

---

Xcodes/Resources/Localizable.xcstrings

I’ve been enjoying using this tool.
I have updated some missing Korean localization strings.
With appreciation. @MattKiazyk

Update Korean localisation

---

Xcodes/Backend/AppState+Runtimes.swift
Xcodes/Resources/Localizable.xcstrings

- Allows cancelling of runtime downloads. 
- Cleans up some localization for runtime alerts.

allow cancelling of runtime downloads, cleanup

---

Xcodes/Resources/Localizable.xcstrings

This PR is to translate some missing strings in the PT-BR localization file.

Fixes Brazilian Portuguese translations

---

Xcodes/Resources/Localizable.xcstrings

Add translations for:
%1$@ (%2$@)  ->  %1$@ (%2$@)
PIN not set  ->  没有设置 PIN

Update zh_Hans translations.
